# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Text_To_Audio.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13Text_To_Audio.proto\"\x18\n\x08Sentence\x12\x0c\n\x04sent\x18\x01 \x01(\t\"\x16\n\x05\x41udio\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32\x38\n\x0bTextToAudio\x12)\n\x12\x43onvertTextToAudio\x12\t.Sentence\x1a\x06.Audio\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Text_To_Audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENTENCE']._serialized_start=23
  _globals['_SENTENCE']._serialized_end=47
  _globals['_AUDIO']._serialized_start=49
  _globals['_AUDIO']._serialized_end=71
  _globals['_TEXTTOAUDIO']._serialized_start=73
  _globals['_TEXTTOAUDIO']._serialized_end=129
# @@protoc_insertion_point(module_scope)
